"""removing relation between sale and processed

Revision ID: 484ee0348bb5
Revises: 6945fb576d60
Create Date: 2025-04-28 20:05:19.660628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484ee0348bb5'
down_revision = '6945fb576d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('sale_processed_stock_id_fkey', type_='foreignkey')
        batch_op.drop_column('processed_stock_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_stock_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sale_processed_stock_id_fkey', 'processed_stock', ['processed_stock_id'], ['id'])

    # ### end Alembic commands ###
