"""added user table to the db

Revision ID: 50bd48282c3c
Revises: 8fec20da1ee2
Create Date: 2025-04-26 22:48:53.198525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50bd48282c3c'
down_revision = '8fec20da1ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('machinery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_service_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_service_due', sa.Date(), nullable=True))

    with op.batch_alter_table('processed_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False, server_default='Groundnut'))
        batch_op.add_column(sa.Column('quantity_kg', sa.Float(), nullable=False, server_default='500'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('processed_stock_raw_stock_id_fkey', type_='foreignkey')
        batch_op.drop_column('raw_stock_id')
        batch_op.drop_column('expected_weight')

    with op.batch_alter_table('service_schedule', schema=None) as batch_op:
        batch_op.alter_column('service_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_schedule', schema=None) as batch_op:
        batch_op.alter_column('service_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('processed_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('raw_stock_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('processed_stock_raw_stock_id_fkey', 'raw_stock', ['raw_stock_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('quantity_kg')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('machinery', schema=None) as batch_op:
        batch_op.drop_column('next_service_due')
        batch_op.drop_column('last_service_date')

    op.drop_table('users')
    # ### end Alembic commands ###
