"""removed relation between raw_stock and processed stock

Revision ID: 6945fb576d60
Revises: 8c6811232a46
Create Date: 2025-04-26 17:58:05.793348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6945fb576d60'
down_revision = '8c6811232a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False, server_default='Groundnut'))
        batch_op.add_column(sa.Column('quantity_kg', sa.Float(), nullable=False, server_default='500'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('processed_stock_raw_stock_id_fkey', type_='foreignkey')
        batch_op.drop_column('expected_weight')
        batch_op.drop_column('raw_stock_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_stock_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expected_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('processed_stock_raw_stock_id_fkey', 'raw_stock', ['raw_stock_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('quantity_kg')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
