"""Added the product_name to raw_stock

Revision ID: 6cc63c6714eb
Revises: 484ee0348bb5
Create Date: 2025-05-05 12:50:52.595735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc63c6714eb'
down_revision = '484ee0348bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_stock', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['product_name'])

    with op.batch_alter_table('raw_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_stock', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    with op.batch_alter_table('processed_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
