"""Added last_service_date and next_service_due to Machinery

Revision ID: 8c6811232a46
Revises: 97ddd1ae436d
Create Date: 2025-04-26 12:43:55.008160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c6811232a46'
down_revision = '97ddd1ae436d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machinery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_service_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_service_due', sa.Date(), nullable=True))

    with op.batch_alter_table('service_schedule', schema=None) as batch_op:
        batch_op.alter_column('service_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_schedule', schema=None) as batch_op:
        batch_op.alter_column('service_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('machinery', schema=None) as batch_op:
        batch_op.drop_column('next_service_due')
        batch_op.drop_column('last_service_date')

    # ### end Alembic commands ###
