"""empty message

Revision ID: 8fec20da1ee2
Revises: ca10e3c2c4ec
Create Date: 2025-04-24 00:48:23.862082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fec20da1ee2'
down_revision = 'ca10e3c2c4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('processed_stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('date_sold', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], ),
    sa.ForeignKeyConstraint(['processed_stock_id'], ['processed_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('distributor')
    # ### end Alembic commands ###
